#!/usr/bin/env python3
"""Apply this builder's edits to an upstream AutoPTZ checkout (guarded).

Run with the current working directory set to the root of a *fresh upstream
checkout*. Every edit asserts it matched exactly what was expected, so any
upstream drift fails the build loudly instead of silently shipping an unpatched
(or mis-patched) release.

This script makes three edits (see PATCHES.md for the full rationale):
  - updater redirect — write a PyInstaller runtime hook that sets
    AUTOPTZ_UPDATE_REPO (upstream's public override) + a guarded spec edit to
    register it; upstream's updater logic is left untouched
  - version stamp — __version__ + the two Apple CFBundle version fields
  - dependency pins — boxmot exact-pin + a platform-marker torch/numpy split

Source-code fixes are carried separately as ``patches/*.patch`` and applied with
``git apply`` before this script runs.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from collections.abc import Callable

# ── dependency pins ────────────────────────────────────────────────────────────
# The numpy/torch break is macOS-Intel-ONLY: the last torch x86_64-macOS wheel is
# 2.2.2, and numpy-2 ABI support starts at torch 2.3.0 — which dropped Intel-mac
# wheels. So Windows / Linux / arm64-macOS resolve a modern torch (>=2.3) that
# works with numpy 2.2.6, and only Intel mac must fall back to torch 2.2.2 +
# numpy<2. The ``torch>=2.3`` floor is required: torch wheels declare no numpy
# upper bound, so without it pip could backtrack to 2.2.2 on Linux/Windows and
# pair it with numpy 2 -> runtime "_ARRAY_API not found" ABI crash.
_INTEL_MAC = 'sys_platform == "darwin" and platform_machine == "x86_64"'
# PEP 508 markers have no "not" operator, so the complement of _INTEL_MAC is
# spelled out via De Morgan's law rather than "not (...)".
_NOT_INTEL_MAC = 'sys_platform != "darwin" or platform_machine != "x86_64"'

_TRACKING_PINS = (
    "boxmot==19.0.0\n"
    "# torch/numpy is macOS-Intel-only: Intel caps torch at 2.2.2 (last x86_64\n"
    "# wheel, needs numpy<2); every other platform takes a numpy-2-compatible\n"
    "# torch>=2.3. The >=2.3 floor stops pip backtracking into the numpy-2 ABI trap.\n"
    f"torch==2.2.2; {_INTEL_MAC}\n"
    f"torchvision==0.17.2; {_INTEL_MAC}\n"
    f"torch>=2.3,<3; {_NOT_INTEL_MAC}\n"
    f"torchvision>=0.18,<1; {_NOT_INTEL_MAC}"
)

_NUMPY_SPLIT = (
    f"numpy==1.26.4; {_INTEL_MAC}\n"
    f"numpy==2.2.6; {_NOT_INTEL_MAC}"
)


def sub_once(
    path: str,
    pattern: str,
    repl: Callable[[re.Match[str]], str],
    desc: str,
    *,
    flags: int = 0,
) -> None:
    """Replace exactly one regex match in ``path`` or exit non-zero."""
    p = pathlib.Path(path)
    if not p.exists():
        sys.exit(f"apply_edits: {path} is missing — upstream layout changed ({desc})")
    text = p.read_text()
    new_text, n = re.subn(pattern, repl, text, count=1, flags=flags)
    if n != 1:
        sys.exit(
            f"apply_edits: expected exactly 1 match for '{desc}' in {path}, got {n}"
            " — upstream layout changed"
        )
    p.write_text(new_text)
    print(f"apply_edits: {desc} -> {path}")


def apply_edits(repo: str, version: str, short_version: str, build_number: str) -> None:
    # ── updater redirect via a PyInstaller runtime hook ───────────────────────
    # Rather than patch upstream's updater *logic* (checker.DEFAULT_REPO), drop a
    # builder-owned runtime hook that sets AUTOPTZ_UPDATE_REPO — the public
    # override checker._repo() already honours — before any autoptz code imports.
    # setdefault means a user who sets their own AUTOPTZ_UPDATE_REPO still wins,
    # and checker.py is left byte-for-byte upstream (nothing to drift against).
    hook_path = pathlib.Path("packaging/rthook_autoptz_update.py")
    hook_path.write_text(
        "# Auto-generated by the builder (scripts/apply_edits.py); do not edit.\n"
        "# Point the in-app updater at the repo that produced this build via\n"
        "# upstream's public AUTOPTZ_UPDATE_REPO override. setdefault so a user's\n"
        "# own value still wins.\n"
        "import os\n\n"
        f"os.environ.setdefault({'AUTOPTZ_UPDATE_REPO'!r}, {repo!r})\n"
    )
    print(f"apply_edits: wrote runtime hook -> {hook_path}")
    # Spec-file builds ignore the --runtime-hook CLI flag, so the hook must be
    # registered inside the spec. SPEC_DIR is defined near the top of the spec.
    sub_once(
        "packaging/autoptz.spec",
        r"runtime_hooks=\[\]",
        lambda _m: 'runtime_hooks=[str(SPEC_DIR / "rthook_autoptz_update.py")]',
        "register runtime hook in spec",
    )

    # ── version stamp (single source drives updater + DMG filename) ───────────
    # Stamped BEFORE the editable install so importlib.metadata agrees.
    sub_once(
        "autoptz/__init__.py",
        r'__version__ = "[^"]+"',
        lambda _m: f'__version__ = "{version}"',
        "autoptz.__version__",
    )
    # Apple bundle fields must be numeric-dotted (a PEP 440 .postN is invalid),
    # so the marketing string carries X.Y.Z and CFBundleVersion a monotonic build
    # number. Both keys hold the same default value, so anchor on each <key>.
    sub_once(
        "packaging/Info.plist",
        r"(<key>CFBundleShortVersionString</key>\s*<string>)[^<]+(</string>)",
        lambda m: m.group(1) + short_version + m.group(2),
        "CFBundleShortVersionString",
    )
    sub_once(
        "packaging/Info.plist",
        r"(<key>CFBundleVersion</key>\s*<string>)[^<]+(</string>)",
        lambda m: m.group(1) + build_number + m.group(2),
        "CFBundleVersion",
    )

    # ── dependency pins (platform-marker split) ───────────────────────────────
    sub_once(
        "requirements/tracking.txt",
        r"^boxmot>=10\.0\.91$",
        lambda _m: _TRACKING_PINS,
        "boxmot/torch pins",
        flags=re.MULTILINE,
    )
    sub_once(
        "requirements/base.txt",
        r"^numpy==2\.2\.6$",
        lambda _m: _NUMPY_SPLIT,
        "numpy marker-split",
        flags=re.MULTILINE,
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", required=True, help="owner/name for the in-app updater")
    ap.add_argument("--version", required=True, help="full PEP 440 version, e.g. 2.2.0.post1")
    ap.add_argument("--short-version", required=True, help="Apple marketing version X.Y.Z")
    ap.add_argument("--build-number", required=True, help="monotonic numeric CFBundleVersion")
    args = ap.parse_args(argv)
    apply_edits(args.repo, args.version, args.short_version, args.build_number)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
